spring:
  datasource:
    url: jdbc:mysql://${MYSQL_HOST}:${MYSQL_PORT}/${MYSQL_DBNAME}?allowMultiQueries=true&autoReconnect=true
    username: ${MYSQL_USER}
    password: ${MYSQL_PASSWORD}
    driverClassName: com.mysql.cj.jdbc.Driver
    hikari:
      maxLifeTime: 400000
      minimumIdle: 2
      maximumPoolSize: 20
      idleTimeout: 120000
      connectionTimeout: 300000
      leakDetectionThreshold: ${MYSQL_HIKARI_LEAK_DETECTION_THRESHOLD:300000}
  jpa:
    properties:
      hibernate:
        show_sql: ${SQL_QUERIES_LOGGING_ENABLED}
logging:
  level:
    org.springframework.web: INFO
    com.backend.vids: ${SVC_LOG_LEVEL}

management:
  endpoints:
    web:
      base-path:
      exposure:
        include: [ health ]

server:
  servlet:
    context-path: "/vids-api"

app:
  jwt:
    key: ${JWT_SECRET_KEY}