CREATE TABLE USERS
(
    ID    INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME  VARCHAR(45)     NOT NULL,
    EMAIL VARCHAR(255)    NOT NULL,
    PASSWORD VARCHAR(255) NOT NULL,
    CREATED_ON   TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE(EMAIL)
);