CREATE TABLE USER_ROLE
(
    ID    INT UNSIGNED AUTO_INCREMENT  PRIMARY KEY,
    USER_ID  INT UNSIGNED   NOT NULL,
    ROLE_ID  INT UNSIGNED   NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS(ID),
    FOREIGN KEY (ROLE_ID) REFERENCES ROLES(ID),
    UNIQUE(USER_ID,ROLE_ID)
);
