CREATE TABLE FOLDERS
(
    ID    INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    NAME  VARCHAR(45)     NOT NULL,
    ROLE_REQUIRED VARCHAR(45)     NOT NULL,
    CREATED_ON   TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE(NAME)
);