CREATE TABLE VIDEOS
(
    ID    INT UNSIGNED AUTO_INCREMENT PRIMARY KEY,
    FOLDER_ID INT UNSIGNED,
    NAME  VARCHAR(45)     NOT NULL,
    LINK VARCHAR(255)    NOT NULL,
    FOREIGN KEY (FOLDER_ID) REFERENCES FOLDERS(ID),
    CREATED_ON   TIMESTAMP       NOT NULL DEFAULT NOW(),
    UNIQUE(NAME)
);