name: PI Development Workflow
on:
  push:
    branches:
      - main
env:
  DOCKER_HUB_IMAGE_ID: matlock0o/backend-videos:backend-apis-${{ github.sha }}
  DOCKER_HUB_TAG: "*DOCKER HUB IMAGE:* pi-export-service-${{ github.sha }}"
  MAVEN_USERNAME: ${{ secrets.PI_PAT_USERNAME }}
  MAVEN_TOKEN: ${{ secrets.PI_PAT_TOKEN }}

jobs:
  workflow:
    name: Build
    runs-on: self-hosted
    permissions:
      id-token: write
      contents: read
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Setup Java Environment
        uses: actions/setup-java@v2
        with:
          java-version: 17
          distribution: adopt
          architecture: x64
      - name: Set up Maven
        uses: stCarolas/setup-maven@v4.5
        with:
          maven-version: 3.8.2
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_HUB_SECRET }}
      - name: Build Java Jar
        run: mvn -e clean install -DskipTests
      - name: Docker Hub Build
        run: docker build -t ${{ env.DOCKER_HUB_IMAGE_ID }} .
      - name: Push to Docker Hub
        run: docker push ${{ env.DOCKER_HUB_IMAGE_ID }}